php-tuf/php-tuf

.github/workflows/php.yml
composer.json

Bump minimum PHP to 7.2.

---

src/Client/DurableStorage/FilesystemDurableStorage.php
src/Client/DurableStorage/ValidatingArrayAccessAdapter.php
src/Client/Updater.php
src/Exception/NotFoundException.php
tests/DurableStorage/InMemoryBackend.php
tests/DurableStorage/ValidatingArrayAccessAdapterTest.php

This is for abstracting get/set of a TUF client's durable state.

Add ArrayAccess-based DurableStorage

---

src/Client/DurableStorage/DurableStorageAccessValidator.php
src/Client/DurableStorage/FileStorage.php
src/Client/Updater.php
tests/Client/UpdaterTest.php
tests/DurableStorage/DurableStorageAccessValidatorTest.php
tests/DurableStorage/MemoryStorage.php

Improve storage class naming. (Split off from https://github.com/php-tuf/php-tuf/pull/18.)

Improve storage class naming and documentation

---

src/Client/Updater.php

One more small separate scope for review. Soft-blocker for #18.

Add datetime conversion helper from #18

---

src/Client/Updater.php
src/Exception/PotentialAttackException/SignatureThresholdExpception.php
tests/Client/UpdaterTest.php
tests/DurableStorage/DurableStorageAccessValidatorTest.php
tests/TestHelpers/DurableStorage/MemoryStorage.php
tests/TestHelpers/DurableStorage/MemoryStorageLoaderTrait.php
tests/Unit/Client/UpdaterTest.php

* Allow phpcs warnings to pass the build
* Add some specific exceptions

Workflow steps 2.2, 2.3

---

src/Client/Updater.php
src/KeyDB.php
src/Metadata/RootMetadata.php
src/RoleDB.php
tests/Client/UpdaterTest.php

Currently work off of https://github.com/php-tuf/php-tuf/pull/55

Use metadata class files for RoleDb and KeyDb

---

composer.json
phpcs-ruleset.xml
phpunit.xml
src/Client/Updater.php
src/Exception/MetadataException.php
src/KeyDB.php
src/Metadata/ConstraintsTrait.php
src/Metadata/MetadataBase.php
src/Metadata/RootMetadata.php
src/Metadata/SnapshotMetadata.php
src/Metadata/TargetsMetadata.php
src/Metadata/TimestampMetadata.php
src/RoleDB.php
tests/DurableStorage/DurableStorageAccessValidatorTest.php
tests/Metadata/MetaDataBaseTest.php
tests/Metadata/RootMetadataTest.php
tests/Metadata/SnapshotMetadataTest.php
tests/Metadata/TargetsMetadataTest.php
tests/Metadata/TimestampMetadataTest.php
tests/TestHelpers/DurableStorage/MemoryStorageLoaderTrait.php
tests/TestHelpers/UtilsTrait.php
tests/Unit/Client/UpdaterTest.php

Against https://github.com/php-tuf/php-tuf/pull/18 for now

Repo Metadata validation

---

.github/workflows/php.yml
composer.json

Require latest version of phpcs for PHP 8 compatibility

---

src/Client/DurableStorage/FileStorage.php
tests/Unit/FileStorageTest.php

Add unit test for FileStorage

---

generate_fixtures.py
tests/Client/UpdaterTest.php
tests/TestHelpers/DurableStorage/MemoryStorage.php
tests/TestHelpers/DurableStorage/MemoryStorageTest.php

This will replace the outdated #76 
This will just create a Rollback attack fixture.

Create a rollback attack repo and test

---

.github/workflows/php.yml

Test against all major supported versions of dependencies

---

src/Metadata/TargetsMetadata.php
tests/Metadata/TargetsMetadataTest.php

Add a method to get expected length of a known target

---

src/Client/GuzzleFileFetcher.php

This is just an internal refactoring -- when using cURL as its backend, Guzzle supports a progress callback function which can abort the transfer if too many bytes come in. Let's use that to enforce the maximum download size.
Additionally, Guzzle's stream system lets us directly get the size of the stream without necessarily having to read it into memory. This would be quite beneficial for, say, larger file downloads. So I propose we leverage that when checking the transfer size after the fact (which we still need to do, in case cURL is not used as the backend). As a fallback, we should keep the existing code which reads N bytes into memory and verifies the maximum download size.

Use progress callback and stream size in GuzzleFileFetcher to enforce maxBytes

---

README.md
SECURITY.md

We have https://github.com/php-tuf/php-tuf/issues/25 to define security policies but in the meantime we should be extra clear this library should not yet be considered secure or be used in production

make clear we are not secure yet

---

src/Client/GuzzleFileFetcher.php
src/Client/Updater.php
src/Metadata/MetaFileInfoTrait.php
src/Metadata/MetadataBase.php
tests/Client/TestRepo.php
tests/Client/UpdaterTest.php
tests/Metadata/MetaDataBaseTest.php
tests/Metadata/RootMetadataTest.php
tests/Metadata/SnapshotMetadataTest.php
tests/Metadata/TargetsMetadataTest.php
tests/Metadata/TimestampMetadataTest.php
tests/Metadata/UntrustedExceptionTrait.php
tests/Unit/GuzzleFileFetcherTest.php

Pretty sure I got all of them but if I missed anything do let me know.

Uncapitalized the 'd' in metadata in functions, variables, comments etc

---

src/Client/GuzzleFileFetcher.php
src/Client/RepoFileFetcherInterface.php
src/Client/Updater.php
src/Metadata/MetaFileInfoTrait.php
src/Metadata/MetadataBase.php
tests/Client/TestRepo.php
tests/Client/UpdaterTest.php
tests/Metadata/MetaDataBaseTest.php
tests/Metadata/RootMetadataTest.php
tests/Metadata/SnapshotMetadataTest.php
tests/Metadata/TargetsMetadataTest.php
tests/Metadata/TimestampMetadataTest.php
tests/Metadata/UntrustedExceptionTrait.php
tests/Unit/GuzzleFileFetcherTest.php

Changed the few that got away!

Metadata changes

---

generate_fixtures.py

This is to support testing any fix to #154.

Fixtures: Threshold = 2 and Related Attack

---

DEPENDENCIES.md

150: Updated the DEPENDENCIES.md file with info on current php-tuf dependencies.
Issue: https://github.com/php-tuf/php-tuf/issues/150

150 Update the DEPENDENCIES.md file

---

src/Exception/RoleExistsException.php
src/RoleDB.php

- 61: Added a new typed exception for when role already exists while adding role.
- https://github.com/php-tuf/php-tuf/issues/61
@tedbow 
This is an MR to see if I'm on the right track for standardizing our exception logic. I'll look for other exceptions to refactor after initial code review of this.
…ding role.

61 Added Typed Exception for Role Exists

---

generate_fixtures.py
tests/Client/UpdaterTest.php

For #141 to test nested delegation we need a test fixture. Here one is. We could still tweak it for our tests later but this has the basics

Create a test fixture with a nested delegation

---

tests/Client/UpdaterTest.php
tests/Metadata/MetaDataBaseTest.php
tests/Metadata/RootMetadataTest.php
tests/Metadata/UnsupportedFieldsTestTrait.php
tests/TestHelpers/UtilsTrait.php

Just noticed when doing other things

clean up UtilsTrait and non-static calls to its methods

---

README.md
src/Client/Updater.php
src/Key.php
src/KeyDB.php
src/Metadata/MetaFileInfoTrait.php
src/Role.php
src/RoleDB.php
tests/Client/UpdaterTest.php
tests/Metadata/SnapshotMetadataTest.php
tests/Metadata/TimestampMetadataTest.php

Based on `https://github.com/theupdateframework/specification/compare/v1.0.9...v1.0.10#diff-b0020aab85257910a5a31f248c201a81cb35e1939545c4b45515e9049e78cdff`.

Update TUF spec implementation to 1.0.10.

---

README.md
src/Client/Updater.php
src/Key.php
src/KeyDB.php
src/Role.php
src/RoleDB.php
tests/Client/UpdaterTest.php

This is just a straight search-and-replace, as the spec has no substantive changes in this iteration (see `https://github.com/theupdateframework/specification/compare/v1.0.10...v1.0.11`).

Update to v1.0.11 of TUF spec

---

README.md
src/Client/Updater.php
src/Key.php
src/KeyDB.php
src/Role.php
src/RoleDB.php
tests/Client/UpdaterTest.php

This PR updates our TUF spec to v1.0.12. As with #194, this is a simple search and replace, because there is no functional change in the spec. (See `https://github.com/theupdateframework/specification/compare/v1.0.11...v1.0.12` for reference.)

Update TUF spec to v1.0.12

---

README.md
src/Client/Updater.php
src/Key.php
src/KeyDB.php
src/Role.php
src/RoleDB.php
tests/Client/UpdaterTest.php

No functional changes, according to `https://github.com/theupdateframework/specification/compare/v1.0.13...v1.0.15`.

Update TUF spec to 1.0.15

---

src/Client/Updater.php
src/Helper/Clock.php
tests/Client/TestUpdater.php
tests/Client/UpdaterTest.php
tests/TestHelpers/TestClock.php

Talked with @TravisCarden and @effulgentsia  about this. Create a new `Clock` class that we replace for testing

Use real now instead of fake when not testing

---

generate_fixtures.py

we know have test fixture where we need to make many delegations. Lets make a function for that

create python function for creating delegations

---

README.md
src/Client/Updater.php
src/Key.php
src/KeyDB.php
src/Metadata/Verifier/FileInfoVerifier.php
src/Metadata/Verifier/RootVerifier.php
src/Metadata/Verifier/SnapshotVerifier.php
src/Metadata/Verifier/TargetsVerifier.php
src/Metadata/Verifier/TimestampVerifier.php
src/Role.php
src/RoleDB.php
tests/Client/UpdaterTest.php

I don't _think_ this had functional changes, but the format of the spec changed and there was a renumbering, so I went through it section by section to confirm the numbering. Hopefully I didn't miss anything, but this should definitely be thoroughly reviewed.
See https://theupdateframework.github.io/specification/v1.0.17.

Update TUF spec to 1.0.17

---

fixtures/TUFTestFixtureThresholdTwoAttack/__init__.py
generate_fixtures.py

...and remove the old TUFTestFixtureBase stuff.

Port TUFTestFixtureThresholdTwoAttack to FixtureBuilder

---

tests/Client/UpdaterTest.php

I was going to start making the tests for the fixtures in #216 
I realized we were going to have do tests like  `testVerifiedDelegatedDownload()`  but with a different fixture set
This PR: changes `testVerifiedDelegatedDownload()` to use a dataprovider which will allow testing other fixtures. to 
It also allows the test to confirm which  json files downloaded only for a specific target file because for each test case only 1 file is downloaded.

change testVerifiedDelegatedDownload to use a dataprovider. 

---

tests/Client/UpdaterTest.php

I think that assertClientFileVersions() and expectedFileVersions would be clearer names for these things. This is a straight-up search and replace.

Rename assertClientRepoVersions() and expectedClientVersions for clarity

---

tests/Client/TestRepo.php
tests/Client/UpdaterTest.php
tests/Metadata/FactoryTest.php
tests/Metadata/MetaDataBaseTest.php
tests/Metadata/RootMetadataTest.php
tests/Metadata/TargetsMetadataTest.php
tests/Metadata/UnsupportedFieldsTestTrait.php
tests/Metadata/UntrustedExceptionTrait.php

Just what it says on the tin. A few simple renames, for clarity purposes.

Improve variable names in tests

---

.github/workflows/build.yml
composer.json

Make the Guzzle HTTP client a Composer suggestion and move it to dev dependencies

---

.github/workflows/build.yml

This adds a check for dependencies for known security vulnerabilities to CI builds.

Add known security vulnerabilities check on CI

---

src/Client/SignatureVerifier.php
src/KeyDB.php
tests/KeyDBTest.php

Fixes #168 by adding test coverage.

Add explicit test coverage for unsupported key types

---

src/Metadata/TargetsMetadata.php
tests/Metadata/TargetsMetadataTest.php

Relates to #301: Make delegations optional.

---

README.md
src/Client/Updater.php
src/Key.php
src/KeyDB.php
src/Role.php
src/RoleDB.php
tests/Client/UpdaterTest.php

See https://github.com/theupdateframework/specification/compare/v1.0.18...v1.0.19.

Update TUF spec to 1.0.19

---

.github/workflows/specification-version-check.yml
README.md
src/Key.php
src/KeyDB.php
src/Role.php
src/RoleDB.php

See https://github.com/theupdateframework/specification/compare/v1.0.19...v1.0.20.

Update TUF spec to v1.0.20

---

.github/workflows/specification-version-check.yml
README.md
src/Key.php
src/KeyDB.php
src/Role.php
src/RoleDB.php

See https://github.com/theupdateframework/specification/compare/v1.0.21...v1.0.22
This one's real easy; just some phrasing changes to clarify how to interact with root metadata. We're already compliant.

Update TUF spec to v1.0.22

---

.github/workflows/specification-version-check.yml
README.md
src/Key.php
src/KeyDB.php
src/Role.php
src/RoleDB.php

https://github.com/theupdateframework/specification/compare/v1.0.28...v1.0.29
Actually *no* changes here! Just an acronym expansion.

Update TUF spec to v1.0.29

---

.github/workflows/specification-version-check.yml
README.md
src/Client/SignatureVerifier.php
src/Key.php
src/Role.php

Fixes #338.
As far as I can tell, there are no behavior changes: https://github.com/theupdateframework/specification/compare/v1.0.31...v1.0.32

Bump spec version to 1.0.32

---

.github/workflows/build.yml

It's broken again, for weird Python reasons. Not sure how fix it, so let me flail around until something works.

Fix CI pipeline

---

src/Client/Updater.php

As part of the project to make delegation searches parallel, we need to identify the roles we want to search up-front, rather than iteratively. So, let's do that -- we should only search roles that match the path of the target, up to the first terminating role. This means we can also remove a level of nesting from our code.

Filter irrelevant delegated roles up front

---

.github/workflows/build.yml
composer.json

PHP 8.0 is no longer supported

Drop support for PHP 8.0

---

.github/workflows/build.yml
.github/workflows/drupal.yml
src/Client/Repository.php
src/DelegatedRole.php
src/Exception/Attack/InvalidHashException.php
src/Exception/NotFoundException.php
src/Metadata/TargetsMetadata.php
src/Metadata/Verifier/SnapshotVerifier.php
src/Metadata/Verifier/TargetsVerifier.php
tests/Metadata/MetaDataBaseTest.php
tests/Metadata/TargetsMetadataTest.php
tests/TestHelpers/TestRepository.php
tests/TestHelpers/UtilsTrait.php

PHP 8.4 has been out for aeons and we don't test on it. Let's fix that, and fix any deprecations arising from that.

Test on PHP 8.4
