requirements.txt

In order to run the server-side (python-based)
implementation, the requirements.txt as
described in the README.md should be re-added.

[BUGFIX] Re-add requirements.txt

---

composer.json
phpcs-ruleset.xml
src/Client/DurableStorage/FilesystemDurableStorage.php
src/Client/Updater.php
tests/Client/UpdaterTest.php
tests/DurableStorage/InMemoryBackend.php

Per discussion on the call early this morning. We were being inconsistent. Folks who were around at the time (@tedbow @xjm @mbaynton others?) decided on camelCase because it's probably more familiar to non-Drupal projects and any little niceties we can do for broader adoption are good.

Move to and enforce camelCase vars and params

---

README.md
composer.json
src/Client/Updater.php
tests/Client/UpdaterTest.php

To allow applications to provide their database/filesystem/whatever implementation.
This also updates the tests to use an in-memory copy of the fixtures so
that the test runs are free to write back to the local repo without
creating lasting side-effects.

Require storage implementation in the constructor

---

src/Exception/FormatException.php
src/Exception/NotFoundException.php

The existing typed `FormatException` and `NotFoundException` classes have some member properties and methods that are never used again:
- `NotFoundException` adds _public_ properties that are never used after initialization.
- `FormatException` adds a protected property and public getter for it that are also never used after initialization.
If we want additional API on the exceptions in the future, we can add it back, but ideally we should not define any public API unless it's used to avoid the need to provide BC for stuff we don't actually need. Offhand, I can't think of a single time I've needed custom API for an exception after it's thrown aside from the exception type itself.
The PR also adds the missing API docs and signature typehints for these two exception classes.

Remove unneeded public and protected members from custom exception classes, and add docs and typehints

---

tests/KeyDBTest.php

* Fix $metadata parameter name to match documentation.
* Label data provider arrays with parameter names.
* Code style nitpicks.
* Tweet-length lines are no longer CI fails, so remove concatenation workaround. Also, add missing trailing commas.
* While $want is an amusing parameter name, it is not totally clear. $expected is more standard for a test.
* Add missing typehints and class and method docs.

Clean up KeyDBTest

---

README.md

The prior link is an archived GitHub repository. An updated PEP 458,
documenting the proposed integration of TUF into PyPI, is now maintained
on Python's PEP infrastructure.

Update PEP 458 link in README

---

fixtures/generate.py

Before making this change, this happened on an initial run:
```
$ python generate.py
Traceback (most recent call last):
File "generate.py", line 17, in <module>
shutil.rmtree('tufkeystore/')
File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/shutil.py", line 706, in rmtree
onerror(os.lstat, path, sys.exc_info())
File "/usr/local/Cellar/python@3.8/3.8.5/Frameworks/Python.framework/Versions/3.8/lib/python3.8/shutil.py", line 704, in rmtree
orig_st = os.lstat(path)
FileNotFoundError: [Errno 2] No such file or directory: 'tufkeystore/'
```
This only deletes the directories if they exist.

Make sure directories exist before cleaning them up in test fixture generation

---

.github/workflows/php.yml

I created https://github.com/php-tuf/php-tuf/issues/70 to figure out what is going on with phpcs and php 8. The failure looks like a bug.
I think it is better to stop this check for now so there is no confusion about checks on currently supported version of php passing. The actual phpunit tests will still run on PHP 8 and phpcs will run on all versions for PHP 7 that are in our matrix.

remove phpcs from running for php8

---

src/Client/Updater.php
src/KeyDB.php
src/RoleDB.php

It's kind of verbose and redundant for RoleDB::createRoleDBFromRootMetadata() to have the word "RoleDB" in the method name. Same goes for KeyDB::createKeyDBFromRootMetadata().
Let's rename them.

Rename RoleDB::createRoleDBFromRootMetadata and KeyDB::createKeyDBFromRootMetadata for clarity

---

src/Client/GuzzleFileFetcher.php
src/Client/RepoFileFetcherInterface.php
src/Client/Updater.php
tests/Client/TestRepo.php
tests/Unit/GuzzleFileFetcherTest.php

\Tuf\Tests\Client\TestRepo::fetchFile incorrectly returned a false when no file when interface says to throw exception
`\Tuf\Client\Updater::updateRoot()` was depending on the this broken behavior so a new method `\Tuf\Client\RepoFileFetcherInterface::fetchFileIfExists()` was added to make this cleaner.
This fix was in #80  but it is really unrelated just discovered there

\Tuf\Tests\Client\TestRepo::fetchFile interface fix

---

tests/Client/TestRepo.php
tests/Client/UpdaterTest.php
tests/Metadata/MetaDataBaseTest.php
tests/TestHelpers/UtilsTrait.php

#90 fixed the TestRepo class to thrown exception instead of returning FALSE on a file not found. This was originally in #80 but we split it off because it was unrelated. But we forgot to pull out all the test coverage for this fix that was in #80 
This is the test coverage. It will also make #80 even smaller

Add testing for file not file exception

---

src/KeyDB.php
tests/KeyDBTest.php

Work @bircher and @ZeiP at DrupalCon Europe 2020 contribution day.
Originally we were going reroll #49 but we found this bug in the process. 
It was probably caused when we switched from using array to ArrayObjects because they are passed by reference

KeyDB::getKey() will return metadata with unused sha512 'keyid' array key for both 256 and 512 key ids.

---

README.md
src/KeyDB.php
src/RoleDB.php

In most code comments which refer to the TUF spec we specify version 1.0.9. like 
`// TUF-SPEC-v1.0.9 Section 5.1.11.`
But in the readme and other links in comments we link to `master`. 
This changes all the links to `v1.0.9`

Change all URLs to spec to version 1.0.9

---

src/Constraints/Collection.php
src/Constraints/CollectionValidator.php
src/Metadata/SnapshotMetadata.php
tests/Metadata/SnapshotMetadataTest.php

This may not necessary but it seems like there are some optional fields that the Python lib might not support creating.

Throw metadata validation exception on Unsupported fields

---

composer.json

Right now, this package cannot be installed alongside Drupal core 8 or 9, since they require versions of Guzzle and Symfony that we don't declare compatibility with. I'd _guess_ that we are not using any APIs which changed between Guzzle 6 and 7 and Symfony 4 and 5 (although I'm by no means the best informed about that), so we should probably allow core-compatible versions of those packages.

Allow multiple major versions of Symfony and Guzzle

---

src/Client/GuzzleFileFetcher.php
tests/Unit/GuzzleFileFetcherTest.php

By calling `JsonNormalizer::asNormalizedJson()` on the data that it fetches, GuzzleFileFetcher inadvertently removes whitespace from the fetched data -- which technically changes the contents of the string, and thus its SHA256 hash. Oops.
After discussion with @tedbow, there doesn't seem to be any obvious reason why the fetcher would need to normalize the JSON; its job is to fetch some number of bytes from the Internet and return them in an unaltered state. So let's fix this.

GuzzleFileFetcher inadvertently modifies the fetched JSON

---

src/JsonNormalizer.php
tests/Unit/JsonNormalizerTest.php

JsonNormalizer::asNormalizedJson() currently escapes slashes, which is the default behavior, but this accidentally changes the returned JSON in an undesirable way. Although this could affect anything that goes through asNormalizedJson(), this problem especially affects targets metadata, which contains paths that contain slashes, and ultimately causes signature verification to fail.

JsonNormalizer::asNormalizedJson() should not escape slashes

---

src/Client/GuzzleFileFetcher.php
src/Client/RepoFileFetcherInterface.php
src/Client/Updater.php
tests/Client/TestRepo.php
tests/Unit/FileStorageTest.php
tests/Unit/GuzzleFileFetcherTest.php

As we integrate Composer with TUF, it's become obvious that TUF will need to support the ability to fetch metadata and files asynchronously, since this is something Composer does already and is a major part of Composer 2's massive speed improvements. Right now, all our HTTP operations are synchronous, which makes sense for Updater::refresh(), but once the metadata is refreshed, we need to be able to fetch things like Composer's package metadata, and actual package artifacts, asynchronously.
The good news is, Guzzle already has great support for async operations using its own promises library. So we should take advantage of that and require RepoFileFetcher::fetchFile() to always return a promise. This should open the door to TUF downloading things and verifying them asynchronously.

Support asynchronous HTTP requests

---

src/Metadata/TargetsMetadata.php
tests/Metadata/TargetsMetadataTest.php

To get #113 done, we'll need a way to get the known hashes for a target. This adds a method for that to TargetsMetadata, plus test coverage.

Add a method to get known hashes of a target

---

composer.json
src/Client/GuzzleFileFetcher.php
src/Client/RepoFileFetcherInterface.php
src/Client/Updater.php
tests/Client/TestRepo.php
tests/Client/UpdaterTest.php
tests/Unit/GuzzleFileFetcherTest.php

As I've been discovering, we need to be able to handle two kinds of data retrieval from the Internet: strings, and files. I've been trying to figure out how to do this consistently -- in other words, we already use promises for all our HTTP transactions, but what should the promises wrap around if some of the transactions should return strings, and others should just download files without returning their contents?
Having pondered it for a couple of days, I believe the answer is streams, which Guzzle already supports using its own PSR-7 implementation. RepoFileFetcherInterface's promises should always wrap around an instance of StreamInterface, which could be referring either to a string in memory, or a file downloaded on disk (whose path we can retrieve as part of the stream metadata). …

Promises returned by RepoFileFetcherInterface should wrap streams

---

src/Client/Updater.php
tests/Client/TestRepo.php
tests/Client/UpdaterTest.php

Now that we have adopted streams (in #119), we need to support the ability to call `hash_file()` for verification of downloaded data, so that we don't _always_ need to read the entire contents of the stream into memory to compute the hash.
According to https://www.php.net/stream_get_meta_data, streams can have a `uri` metadata property which refers to their source -- which could be a file path, if that's where Guzzle saved the downloaded data. We should leverage that property to see if the stream is coming from a (downloaded) file, and use hash_file() in that case.

Use hash_file() to verify file streams where appropriate

---

src/Client/GuzzleFileFetcher.php
src/Client/ResponseAwareStream.php
src/Client/ResponseStream.php

In some cases, consumers of TUF (right now, that means php-tuf/composer-integration) will need information about the HTTP response that came back from a request. Right now, though, our promises wrap streams -- which is good. The streams have zero awareness about the response (or even that they were produced by an HTTP transaction) -- which is also good. But for integrating with Composer (and possibly other things), it's too limiting.
I propose to add a simple adapter class which implements `StreamInterface`, and wraps around both a stream _and_ the response which produced the stream. That way, calling code can examine the response if it needs to, but also continue to use the resulting stream as any other.

Add a StreamInterface implementation that is aware of the HTTP response

---

src/Client/GuzzleFileFetcher.php
tests/Unit/GuzzleFileFetcherTest.php

Right now, GuzzleFileFetcher::create() throws an exception if you give it a non-HTTPS URI. Since HTTPS is not the main form of security in TUF, this is needlessly restrictive.

GuzzleFileFetcher::create() should allow HTTP URIs

---

src/Client/GuzzleFileFetcher.php
src/Client/Updater.php

As with #121, this is a minor API change to support Composer integration in a consumer-agnostic way. This will allow the plugin to pass the `sink` option to the Guzzle file fetcher, which will make Guzzle download a target to a specific path (Composer's `HttpDownloader` has a similar functionality, so this lets us parallel that).

Allow file fetchers to accept idiosyncratic options

---

src/Client/Updater.php
tests/Client/UpdaterTest.php

`Updater::download()` is not really doing the right thing if the requested target is either non-existent or has no trusted hashes. It's _supposed_ to return a promise, but instead it's immediately throwing an exception, which means calling code needs to have a try-catch around a promise. That's nuts. Instead, it should just immediately return a rejected promise, which makes more sense given how promises are supposed to work.

Updater::download() should return a rejected promise if the target is invalid

---

src/Client/GuzzleFileFetcher.php
tests/Unit/GuzzleFileFetcherTest.php

The Python repository tool generates the repository in a specific way: TUF metadata goes into a `/metadata` directory, and the actual targets go into `/targets`. GuzzleFileFetcher should make it easier to deal with this layout by optionally remembering the path prefixes for these things.

Support path prefixes for metadata and targets in GuzzleFileFetcher

---

src/Client/GuzzleFileFetcher.php
tests/Unit/GuzzleFileFetcherTest.php

Our plan to sign Packagist packages means that we need to be able to sign targets that live on a separate server. In order to make that work, we need to be able to pass full URLs to GuzzleFileFetcher::fetchTarget(), bypassing the prefixing that we do.

Allow GuzzleFileFetcher::fetchTarget() to bypass prefixing

---

src/Client/GuzzleFileFetcher.php
tests/Unit/GuzzleFileFetcherTest.php

This is related to #128. It may be necessary for us to sign a package using a local copy of the file, but actually _download_ that file, in a runtime situation, from some arbitrary URL. This PR makes the GuzzleFileFetcher (and only that fetcher) support mapping a local target path to an arbitrary URL.

Allow targets to be downloaded from arbitrary URLs

---

src/Client/Updater.php
src/Exception/PotentialAttackException/InvalidHashException.php
tests/Client/UpdaterTest.php

In order to get around the fact that the Composer integration plugin doesn't handle 304 responses, we need to be able to convert an InvalidHashException caused by a 304 to a legitimate response object. In order to do *that*, we need some way for calling code to access the stream that caused the InvalidHashException. This PR adds such an accessor.

Make InvalidHashException aware of the offending stream

---

src/KeyDB.php
src/Metadata/MetadataBase.php

For whatever reason, in some circumstances Composer seems to have a problem resolving the deep_copy() function. It looks like it's a pretty thin wrapper anyway; I propose we use the class reference directly.

Stop using deep_copy() function

---

src/Client/Updater.php
src/Metadata/TargetsMetadata.php
tests/Metadata/TargetsMetadataTest.php

Right now, if the updater requests metadata about a specific target and that target is unknown, we throw InvalidArgumentException. Although that technically works, it's very ambiguous to the calling code; it has no real way to know that the exception was thrown by TUF, for TUF-specific reasons. We should use our already-existing NotFoundException instead, which will be a lot clearer to consumers of TUF.

TargetsMetadata should throw a TUF-specific exception for undefined targets

---

src/Exception/NotFoundException.php

Since `$itemType` is printed as the first word in a clause (~sentence), the default value should be capitalized.

Update NotFoundException default item type

---

src/Metadata/TargetsMetadata.php
tests/Metadata/MetaDataBaseTest.php
tests/Metadata/TargetsMetadataTest.php

'custom' is allowed for targets but is ignored by the spec https://github.com/theupdateframework/specification/blob/v1.0.9/tuf-spec.md

Allow 'custom' element on target metadata

---

src/Client/Updater.php
tests/Client/UpdaterTest.php

Rather than requiring calling code to check `$this->isRefreshed`, `Updater::refresh()` should be smart enough to return early if it's already been refreshed. To wit, it should also support a `$force` flag to make it refresh from the server anyway.

Updater::refresh() should return early if already refreshed

---

src/Client/Updater.php
src/Metadata/MetaFileInfoTrait.php
src/Metadata/MetadataBase.php
src/Metadata/TargetsMetadata.php
tests/Metadata/MetaDataBaseTest.php
tests/Metadata/TargetsMetadataTest.php

Role is not always the same as type. Delegate roles will be the type targets' but role specified in the delegation.

Adds getRole method 

---

src/Client/GuzzleFileFetcher.php
src/Client/Updater.php
tests/Client/UpdaterTest.php
tests/Unit/GuzzleFileFetcherTest.php

Right now, it's up to the file fetchers to validate the length of the data they retrieve. Since bounds checking is important in TUF, this is something that the Updater should do itself, by acting on the streams returned from the file fetchers.

Updater should validate the length of a downloaded stream

---

src/Metadata/TargetsMetadata.php
tests/Metadata/TargetsMetadataTest.php
tests/TestHelpers/UtilsTrait.php

Adds TargetsMetadata::getDelegatedKeys() and TargetsMetadata::getDelegatedRoles()

Add helper methods to get delegated info

---

src/Client/Updater.php

Per Seldaek's feedback in composer/composer#9740, it would simplify our integration with Composer if it were possible to verify a downloaded file or string against TUF without relying on TUF to do the downloading too. To that end, let's expose a new `verify()` method which takes a data stream and validates it against a specific known target.

Move verification of downloaded target into new public verify() method

---

src/Client/Updater.php

In https://github.com/php-tuf/php-tuf/pull/141 will repeat downloading other delegated target metadata files. This will be the same logic as `targets.json`.  This refactors it into method so we can reuse it.

Refactor verifying target metadata file into method

---

src/Client/Updater.php
src/Metadata/ConstraintsTrait.php
src/Metadata/MetadataBase.php
src/Metadata/RootMetadata.php
src/Role.php
src/RoleDB.php
tests/Metadata/RootMetadataTest.php
tests/Unit/RoleTest.php

The roleDB is kind of messy. Not only keeps track of roles but also has to know the structure of those roles.
Also `Updater::isKeyIdAcceptableForRole()` could be moved to a new Role class.
In https://github.com/php-tuf/php-tuf/pull/141 we will need more info from special type of role. We could create `DelegatedRole extends Role` with `DelegatedRole::matchTargetPath($target)`

Create Role class

---

composer.json
src/Metadata/MetadataBase.php
tests/Metadata/RootMetadataTest.php
tests/Unit/Client/UpdaterTest.php
tests/Unit/GuzzleFileFetcherTest.php

We not longer need a direct dependency on `phpcodesniffer-composer-installer` now that we have `php-tuf/phpcodesniffer-standard`. This was causing a requirements error.
Also removing unused use statements because of new `php-tuf/phpcodesniffer-standard` rule.

remove phpcodesniffer-composer-installer dependency and unused use statements

---

src/Client/Updater.php

As per discussion with @tedbow, @effulgentsia, and @xjm, we want to hide the implementation of `Updater::verify()` and `Updater::checkLength()` so that consumers of PHP-TUF that need to use their own download mechanism -- like the Composer integration plugin, for example -- can do so by extending `Updater`, but still take advantage of TUF's verification mechanisms.

Make Updater::verify() and ::checkLength() protected

---

src/Exception/InvalidKeyException.php
src/KeyDB.php
tests/KeyDBTest.php

The current implementation of generating multiple key IDs and allowing them to be used is not in line with the spec and opens a security hole, per discussion yesterday with @tedbow

Issue #56 fix use of keyid_hash_algorithms in key data

---

src/Metadata/ConstraintsTrait.php
tests/Metadata/RootMetadataTest.php
tests/Metadata/TargetsMetadataTest.php

In #174  we realized `keyid_hash_algorithms` should not vary and we don't actually need it from metadata to compute the key. Currently in `\Tuf\Metadata\ConstraintsTrait::getKeyConstraints()` we allow any non-empty array of strings. This changes to only except the exact value `["sha256", "sha512"]`

Ensure that keyid_hash_algorithm is equal to exact expected value

---

generate_fixtures.py

#181 we got the delegation paths wrong. 
From the spec https://github.com/theupdateframework/specification/blob/v1.0.9/tuf-spec.md#4-document-formats
> Clients MUST check that a target is in one of the trusted paths of **all roles in a delegation chain**, not just in a trusted path of the role that describes the target file. 
Important part here is **all roles in a delegation chain**
Before we didn't have delegated roles where their `paths` that are a subset of their parent delegation

fix TUFTestFixtureNestedDelegated to have correct paths in delegation chain

---

generate_fixtures.py
src/Metadata/TargetsMetadata.php
tests/Client/UpdaterTest.php
tests/Metadata/SnapshotMetadataTest.php
tests/Metadata/TargetsMetadataTest.php
tests/Metadata/UnsupportedFieldsTestTrait.php

We have #191 to support `path_hash_prefixes` but until then lets throw a validation if it is set

Mark path_hash_prefixes as unsupported

---

README.md
src/Client/Updater.php
src/Key.php
src/KeyDB.php
src/Role.php
src/RoleDB.php
tests/Client/UpdaterTest.php

Updates to spec version 1.0.13, according to the differences in `https://github.com/theupdateframework/specification/compare/v1.0.12...v1.0.13`.
The only functional change here was the introduction of a "now+T" time guard to defend against freeze attacks. I discussed this with @tedbow and we decided that the library's default functionality should be unchanged, but that consumers (like the Composer plugin) should be able to provide an adjusted expiration time if they want to, since the spec says that should be left up to the application using TUF.
Beyond that, there was a re-numbering of the spec sections, and that was a little tricky, so I'd ideally like two sign-offs here before that gets merged.

Update TUF spec to 1.0.13

---

README.md
src/Client/Updater.php
src/Key.php
src/KeyDB.php
src/Role.php
src/RoleDB.php
tests/Client/UpdaterTest.php

Update to v1.0.16 of the spec, according to `https://github.com/theupdateframework/specification/compare/v1.0.15...v1.0.16`.
I'm not even mad that it removes the idea of "fixed update expiration time" that we just implemented in #197. I removed the interval stuff and renamed the method to more accurately summarize what it's for.

Update TUF spec to 1.0.16

---

src/Client/Updater.php

`Updater::refresh()` is a very long method. To make it easier to read through and understand, we should split it up into smaller methods that each handle a coherent piece of the spec. Let's start with section 5.3, which updates timestamp metadata.
This PR doesn't refactor the actual logic in anyway, beyond moving it into its own private method of `Updater`.

Move section 5.3 into its own method

---

src/Client/Updater.php
src/Metadata/Factory.php
src/Metadata/RootMetadata.php
src/Metadata/SnapshotMetadata.php
src/Metadata/TargetsMetadata.php
src/Metadata/TimestampMetadata.php

This is split off from @tedbow's work in #206. IMHO it makes sense for us to have a metadata factory class, which knows how to load trusted metadata from the persistent storage backend. Later on, we can add a method that also loads the appropriate verifier class for the given role.

Create a factory class for loading trusted metadata

---

src/Client/Updater.php
src/Metadata/Factory.php
src/Metadata/MetadataBase.php
tests/KeyDBTest.php
tests/Metadata/RootMetadataTest.php

Currently `\Tuf\Metadata\MetadataBase::setIsTrusted()` allows you to mark metadata as trusted or untrusted.
But there is no reason you would keep metadata object around if you knew it was untrusted. All of our calls to this pass true.
We verify and mark as trusted. You should not be able to mark as untrusted. Untrusted is the default state until the metadata is verified.

Do not allow metadata to be set as untrusted after they are set as trusted

---

generate_fixtures.py
src/Client/Updater.php
tests/Client/UpdaterTest.php

initially when I created getMetadataForTarget() I read the spec wrong and thought if the a role is terminating you don't search more of that delegation tree. But actually this abort the search for the metadata. SEe 5.5.6.2.2 in https://github.com/theupdateframework/specification/blob/v1.0.16/tuf-spec.md
This still needs tests

Fix terminating delegated role logic

---

src/Metadata/Verifier/FileInfoVerifier.php
src/Metadata/Verifier/SnapshotVerifier.php
src/Metadata/Verifier/TimestampVerifier.php

Currently `SnapshotVerifier` and `TimestampVerifier` both extend `FileInfoVerifier`. 
They do this because they both share some logic in checking for rollback attacks, so we have `FileInfoVerifier::checkRollbackAttack()`
This method calls `parent::checkRollbackAttack($untrustedMetadata);` which is `VerifierBase::checkRollbackAttack()` which just checks that new version is not less than the trusted version of the same type.
This seems reasonable but in reviewing #213 I realized that for snapshot the `VerifierBase::checkRollbackAttack()` doesn't apply. It won't break anything to do it but it is not actually in the spec.
Instead it has:
1. **5.4.3. Check against timestamp role's snapshot version.** which we do in 
```
// TUF-SPEC-v1.0.16 Section 5.4.3 …
```

Fix snapshot rollback to not check version in previous snapshot file

---

README.md
src/Key.php
src/KeyDB.php
src/Role.php
src/RoleDB.php

See `https://github.com/theupdateframework/specification/compare/v1.0.17...v1.0.18` for the diff. Doesn't look like there were any functional changes or re-numberings to worry about.

Update TUF spec to 1.0.18

---

fixtures/TUFTestFixtureAttackRollback/__init__.py
generate_fixtures.py

Just what it says! Ports the existing fixture to use the new FixtureBuilder class.

Port TUFTestFixtureRollbackAttack to FixtureBuilder

---

tests/Client/UpdaterTest.php

this will make  testing https://github.com/php-tuf/php-tuf/pull/216 easier and more robust
Add extra arguments to testDelegationErrors() 
This allows testing other fixtures.
Also adding `$expectedClientVersions` allows the test to confirm which roles were evaluated without this confirmation we don't know if a file was not found  because the role was not evaluated or evaluated and  file was still not found.

Add extra arguments to testDelegationErrors() 

---

src/Metadata/Factory.php
tests/Metadata/FactoryTest.php

This adds test for the class in 1 commit and fixes the problem in the next
Discovered this in #216 because need to call `\Tuf\Metadata\TargetsMetadata::getRole()` and it was always returning 'targets' even for delegated roles.

\Tuf\Metadata\Factory doesn't account for delegated roles

---

composer.json
src/KeyDB.php
src/constants.php

Do we really need this file? I don't understand the usefulness. So, if everyone agrees, maybe we just remove it for now...

Remove constants.php

---

src/Client/Updater.php
tests/Client/UpdaterTest.php
tests/Unit/Client/VerifierTest.php

Under `/src` we have done a good attempt to specify which portions of the spec we are implementing but under `/tests` we have not specified where spec portions are tested. 
This adds the comments. There are 2 comments under `/src` also for spec items that were not commented.
In this process I also made #247  to keep track of areas we don't have test coverage for yet. Basically where we can comment out parts of our code and no tests fail

Specify spec numbers in test coverage

---

tests/Client/UpdaterTest.php

I don't think getSystemInTest() should have a default value for $fixturesSet. It should always be clear which fixture you're testing with, and making it a required parameter would make this explicit.

Always pass fixture name to getSystemInTest()

---

tests/Client/UpdaterTest.php

This PR does three interrelated things:
1. It makes `getSystemInTest()` set up `$this->testRepo`.
2. And `$this->localRepo`.
3. It makes `getSystemInTest()` always assert the hard-coded starting versions, for extra safety and consistency.

Move some overhead into getSystemInTest()

---

composer.json
phpcs.xml.dist

The only other project that used `php-tuf/phpcodesniffer-standard` has diverged, so there's no reason to have a separate library for it. This collapses it directly into this project--no changes to the standard itself. Once this is merged, we can delete the whole `php-tuf/phpcodesniffer-standard` repo.

Collapse php-tuf/phpcodesniffer-standard into project

---

.github/workflows/build.yml
README.md
composer.json
src/Client/DurableStorage/DurableStorageAccessValidator.php
src/Client/DurableStorage/FileStorage.php
src/KeyDB.php
src/Metadata/Verifier/FileInfoVerifier.php
tests/Client/UpdaterTest.php
tests/TestHelpers/DurableStorage/MemoryStorage.php
tests/Unit/FileStorageTest.php
tests/Unit/GuzzleFileFetcherTest.php

I propose we drop support for PHP 7, for the following reasons:
* It is EOL. Since this is a security-related, cryptographically-sensitive project, it is a security risk for us to support dead versions of PHP.
* If someone uses PHP-TUF with `ext-sodium` installed, we don't want to inadvertently be using an unsupported, potentially insecure version of the Sodium library built into PHP.
* From the Drupal perspective, we don't really need to require PHP-TUF for _attended_ updates. Therefore, people could still use the Automatic Updates module with PHP 7.4; they'd just need to do their updates in the UI.
* Our tests use Prophecy, which requires PHP 7.3 or later. Additionally, we're currently supporting two major versions of PHPUnit, which leads to awkwardness around deprecated assertions. …

Drop support for PHP 7

---

.github/workflows/build.yml
composer.json

Symfony 6 is the actively supported version of Symfony, and it's also what Drupal 10 requires.
We need to support it, and ensure we're testing with it.

Support Symfony 6

---

.github/workflows/build.yml

I've been seeing some distressing behaviors happening during our CI runs -- uploads and downloads of the generated fixtures will sometimes hang, which requires me to go in and manually cancel and re-run the jobs.
I suspect this may be happening because, according to https://github.com/marketplace/actions/upload-a-build-artifact#too-many-uploads-resulting-in-429-responses, the fixtures are being uploaded as a directory, rather than an archive. With over 1,000 files in the fixtures, it's no wonder that this is causing trouble.
To solve this, I propose that the fixtures be packaged as an archive and uploaded/downloaded that way.

Compress generated fixtures to speed up builds and prevent upload/download failures

---

.github/workflows/build.yml

We should be running our tests every day automatically. Not really controversial. This adds syntax to do that at 3 AM UTC, according to the documentation at https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule.

Run CI workflow every day

---

.github/workflows/build.yml

We have a bit of our GitHub workflow which installs dependencies, ignoring platform requirements if we're testing against PHP 8.
This only ever existed to get around the fact that, previously, we had a requirement on PHP 7, but wanted to test on PHP 8 anyway. Since we have dropped PHP 7 support, we don't need this shim.

Remove unnecessary dependency installation from CI

---

tests/Client/ConsistentFixturesUpdaterTest.php
tests/Client/InconsistentFixturesUpdaterTest.php
tests/Client/UpdaterTest.php
tests/Metadata/SnapshotMetadataTest.php
tests/Metadata/TimestampMetadataTest.php
tests/Unit/Client/VerifierTest.php
tests/Unit/GuzzleFileFetcherTest.php
tests/Unit/RoleTest.php

Our coverage report (`composer coverage`) reports a lot of errors - that is, test methods which cover methods that don't exist. That's because our annotations aren't always correct.
This PR doesn't add or remove any coverage, but it does fix the wrong annotations so that PHPUnit can properly report what's covered and what's not.

Fix incorrect coverage annotations

---

src/Metadata/ConstraintsTrait.php
src/Metadata/MetadataBase.php
src/Metadata/TargetsMetadata.php
src/Metadata/TimestampMetadata.php

It'd be a little easier to read the validation constraints for metadata if we used the constraints' default options where possible. For example, things like `new Type(['type' => 'string'])` can always be converted to `new Type('string')`.
We already do this in several places, but I propose we make it consistent.

Make metadata constraints easier to read by using default options for validation constraints

---

src/Client/Updater.php
tests/Client/UpdaterTest.php

So Updater has a $mirrors property which is not used for anything. UpdaterTest::getSystemInTest() passes something to it, but...it's not used inside Updater for anything.
Really, we just don't support mirrors right now (and might not before 1.0.0). Therefore, we should remove this code.

Remove mirror support from Updater

---

composer.json
src/Loader/SizeCheckingLoader.php
tests/Client/UpdaterTest.php
tests/Unit/SizeCheckingLoaderTest.php

Support non-seekable streams in SizeCheckingLoader

---

composer.json
tests/Unit/SizeCheckingLoaderTest.php

We currently use guzzlehttp/psr7 v1, but it's not compatible with Drupal 10, which requires 2.4 or later. I don't see any real reason not to bump our constraint.

Require guzzlehttp/psr7 to 2.4

---

composer.json

So...since #297, we no longer have any use of the Guzzle HTTP client. So, the suggestion in composer.json to install it is not accurate anymore and should be removed.

Remove guzzlehttp/guzzle from composer.json suggestions

---

composer.json

I'm not convinced we need this as a direct dependency.
We already have a hard dependency on guzzlehttp/psr7, which is by definition an implementation of the interfaces in psr/http-message. So it seems redundant to also depend on psr/http-message. I propose we remove it until -- and if -- we remove guzzlehttp/psr7.

Remove direct dependency on psr/http-message

---

.github/workflows/specification-version-check.yml

The following PR adds a workflow that keeps track and creates an issue for notifying of new TUF specification releases.
The version (v1.0.29) of the spec which is currently used for the verification is added without verifying if this is indeed the version that the `php-tuf` project is compliant with. In that sense, please advise which version to use and I'll update the PR accordingly.
**Note:** Dependent on - https://github.com/theupdateframework/specification/pull/224
Signed-off-by: Radoslav Dimitrov <dimitrovr@vmware.com>

Add workflow responsible for notifying of new TUF spec releases

---

src/Client/DurableStorage/FileStorage.php
src/Client/SignatureVerifier.php
src/Client/Updater.php
src/DelegatedRole.php
src/Exception/Attack/InvalidHashException.php
src/Key.php
src/KeyDB.php
src/Metadata/MetadataBase.php
src/Metadata/TargetsMetadata.php
src/Metadata/Verifier/FileInfoVerifier.php
src/Metadata/Verifier/RootVerifier.php
src/Metadata/Verifier/UniversalVerifier.php
src/Metadata/Verifier/VerifierBase.php
src/Role.php

Because it's 2023, and our minimum supported PHP is 8.0. This removes a pile of annoying boilerplate, and anything that increases type safety is good.

Adopt typed properties and constructor property promotion

---

.github/workflows/specification-version-check.yml
README.md
src/Key.php
src/KeyDB.php
src/Role.php
src/RoleDB.php

Behold: https://github.com/theupdateframework/specification/compare/v1.0.22...v1.0.23
As far as I can tell, we are already compliant with this. When computing hashes and whatnot, we simply do it by canonicalizing everything in `signed`. We don't care what's in there.

Update TUF spec to v1.0.23

---

.github/workflows/specification-version-check.yml
README.md
src/Key.php
src/KeyDB.php
src/Metadata/TargetsMetadata.php
src/Role.php
src/RoleDB.php
tests/Metadata/TargetsMetadataTest.php

See https://github.com/theupdateframework/specification/compare/v1.0.23...v1.0.24
Three relevant bits here:
> An OPTIONAL boolean indicating whether the repository supports consistent snapshots.
This is already optional, and tested in `\Tuf\Tests\Metadata\RootMetadataTest::providerOptionalFields()`.
> DELEGATIONS is an OPTIONAL object
This is also already the case, and tested by `\Tuf\Tests\Metadata\TargetsMetadataTest::providerOptionalFields()`.
> The "path_hash_prefixes" and "paths" attributes are OPTIONAL
Ah, _this_ we needed to change. I did that, and added test coverage in TargetsMetadataTest. I confirmed that removing the `Optional` constraint from `paths` causes the test to fail.

Update TUF spec to v1.0.24

---

.github/workflows/specification-version-check.yml
README.md
src/Key.php
src/KeyDB.php
src/Role.php
src/RoleDB.php

See https://github.com/theupdateframework/specification/compare/v1.0.24...v1.0.25
We already already compliant with this (see, for example, `\Tuf\Metadata\Verifier\SnapshotVerifier::verify()`). We check hashes first, and that seems to be what the correct behavior is, but I think they're just clarifying _why_ it's safe to check the hashes before the signatures.

Update TUF spec to v1.0.25

---

.github/workflows/specification-version-check.yml
README.md
src/Key.php
src/KeyDB.php
src/Role.php
src/RoleDB.php

See https://github.com/theupdateframework/specification/compare/v1.0.26...v1.0.27
This is another easy one. The only change is about how target files _on the server_ are named if consistent snapshots are used. It really doesn't affect us; we have no opinions at all about how target files are named, regardless of whether consistent snapshots are in play.

Update TUF spec to v1.0.27

---

.github/workflows/specification-version-check.yml
README.md
src/Key.php
src/KeyDB.php
src/Role.php
src/RoleDB.php

https://github.com/theupdateframework/specification/compare/v1.0.27...v1.0.28
No real change here. I think they just removed some wording they felt was ambiguous -- the commit message in https://github.com/theupdateframework/specification/commit/c43045a85a637a5e2922af2dc1af08691e496780 is quite clear on that.

Update TUF spec to v1.0.28

---

src/Client/SignatureVerifier.php

In SignatureVerifier, we currently call PHP's `hex2bin()`. According to [PHP's documentation](https://www.php.net/sodium_hex2bin), this function is susceptible to side-channel attacks, whereas `sodium_hex2bin` isn't. Since we already use sodium functions, we should use `sodium_hex2bin` here.

Use sodium_hex2bin

---

src/KeyDB.php
src/Metadata/ConstraintsTrait.php
tests/KeyDBTest.php
tests/Metadata/RootMetadataTest.php
tests/Unit/KeyTest.php

This is some clean-up in the name of brevity. Right now, we do a specific check in KeyDB::addKey() that the incoming key is of a supported type. Given how KeyDB is created (basically it's just pulling directly from some root metadata), there is no reason why we shouldn't just use a validation constraint for this. It's simpler and lets us keep related validation logic in one place.

Use validation constraints to check key type

---

src/Metadata/MetadataBase.php
src/Metadata/Verifier/VerifierBase.php
tests/Unit/Client/VerifierTest.php

Right now, when checking for freeze attacks, we call MetadataBase::getExpires() and convert it to a DateTimeImmutable object. There is, as far as I can tell, no reason not to just, like, return a \DateTimeImmutable from `MetadataBase::getExpires()`. It makes for a simpler API and removes the need for a special conversion method in `VerifierBase`.

MetadataBase::getExpires() should return a DateTimeImmutable object

---

src/DelegatedRole.php
src/Metadata/TargetsMetadata.php
tests/Metadata/TargetsMetadataTest.php
tests/Unit/DelegatedRoleTest.php

Part 2 of fixing #191.
This adds support for `path_hash_prefixes` to the DelegatedRole metadata object, and ensures it's mutually exclusive with `paths`.

Allow DelegatedRole to validate and carry path_hash_prefixes

---

composer.json
src/CanonicalJsonTrait.php
tests/Unit/CanonicalJsonTraitTest.php

These arrays (which are detectable with PHP 8.1's `array_is_list()` function) should not have their keys sorted -- by definition, their keys are already sorted. But we sort them anyway, which results in them being incorrectly canonicalized, and thus causing false negatives during signature verification.
We should use Symfony's PHP 8.1 polyfill to bring in `array_is_list()`, and then ensure we don't sort the keys of indexed arrays when canonicalizing.
This bug manifests on arrays with more than 10 items, because keys like `10`, `11`, and so forth get put after 1, but before 2. So you end up with keys in the wrong order: `1, 10, 11, 2`.

Indexed arrays with >= 10 items are incorrectly canonicalized

---

src/Metadata/TargetsMetadata.php

If a TargetsMetadata object has no `delegations` key, `toCanonicalJson()` will still trigger an "Undefined key `delegations`" error from this bit:
```php
$normalized['delegations']['keys'] = (object) $normalized['delegations']['keys'];
```
We should ensure that $normalized has a `delegations` key before doing this.

TargetsMetadata::toCanonicalJson() can try to access an undefined key

---

src/Client/Repository.php
src/Client/Updater.php
tests/Client/UpdaterTest.php
tests/Unit/RepositoryTest.php

Turns out that, for testing with Drupal's staging metadata, 100,000 bytes is not enough :( Ideally, the size of the metadata to download would be safely encoded by Rugged in `snapshot.json`, and there is an issue for that (https://gitlab.com/rugged/rugged/-/issues/126), but it's unclear when that will be fixed and released.
In the meantime, we should make it possible for Repository::MAX_BYTES to be changed, allowing us to work around this. So I propose we make it a `public static int` instead of a constant. That way, it will affect every instance of `Repository` the same way (thereby acting similarly to a constant), but mutable.

Make Repository::MAX_BYTES a public static int so it can be overridden

---

src/Client/Repository.php
src/Client/Updater.php
tests/TestHelpers/TestRepository.php
tests/Unit/RepositoryTest.php

This is the follow-up of #356.
As part of searching for delegated targets in parallel, we need to be able to fetch targets metadata asynchronously, using promises. We do NOT need to make root, timestamp, or snapshot metadata asynchronous -- they are always loaded and verified in a synchronous manner according to TUF's design. But targets metadata does need to be asynchronous in nature, since that's what we download as we search the delegation tree.
Once this is done, there will be at least one other follow-up to make the logic of `searchDelegatedRolesForTarget()` asynchronous too.

Always fetch targets metadata asynchronously

---

src/Client/DurableStorage/FileStorage.php
tests/Unit/FileStorageTest.php

Right now, we save trusted metadata using whatever role name it has. If the role name has path traversal components (for example, `parent_role/../grandparent_role`), the file would be saved as `path/to/metadata/parent_role/../grandparent_role.json`. That's unauthorized filesystem access.
To fix this, the role name should be URL-encoded. To continue the previous example, it should be saved as `path/to/metadata/parent_role%2F..%2Fgrandparent_role.json` to prevent path traversal.

Prevent path traversal by URL-encoding the names of all saved metadata

---

composer.json

We're not getting anything out of Guzzle 6 except for extra complexity, as well as having to walk carefully around the minefield of compatibility between two different _major_ versions of `guzzlehttp/promises`, which is a library we actually _do_ depend on. Let's drop compatibility with Guzzle 6.
For Drupal's part, it hasn't been compatible with Guzzle 6 since Drupal 9, which is now EOL.

Drop compatibility with Guzzle 6

---

.github/workflows/build.yml

PHP 8.3 has been released for a while now, so it should be in our testing matrix.

Test on PHP 8.3

---

src/Key.php
src/Metadata/ConstraintsTrait.php
tests/FixtureBuilder/Key.php
tests/Metadata/RootMetadataTest.php
tests/Metadata/TargetsMetadataTest.php
tests/Unit/KeyTest.php

The `keyid_hash_algorithms` field is no longer part of the TUF specification: https://theupdateframework.github.io/specification/latest/#file-formats-keys
We should remove support for it and the related test coverage.

Completely remove support for keyid_hash_algorithms

---

composer.json
src/Metadata/ConstraintsTrait.php
src/Metadata/MetadataBase.php
src/Metadata/RootMetadata.php
src/Metadata/SnapshotMetadata.php
src/Metadata/TargetsMetadata.php
src/Metadata/TimestampMetadata.php
tests/Metadata/MetaDataBaseTest.php
tests/Metadata/TargetsMetadataTest.php

This fixes #317.
It also removes the redundant use of `new Type('array')` in places where we're also using `new All([...])`. [The `All` validator ensures that it's given an array or a `Traversable`](https://github.com/symfony/validator/blob/6.1/Constraints/AllValidator.php#L37), which means we don't also need to specify `new Type('array')`. (Maybe we did in earlier versions of Symfony Validator, but it's not necessary in 6.1.)

Use Symfony's Unique constraint where appropriate

---

composer.json

We depend directly on PHP 8.1 or later, so we don't need this polyfill.

Remove Symfony's PHP 8.1 polyfill from dependencies

---

src/Client/Updater.php
src/Metadata/ConstraintsTrait.php
src/Metadata/MetadataBase.php
src/Metadata/Verifier/TrustedAuthorityTrait.php
src/Metadata/Verifier/VerifierBase.php
tests/Metadata/MetaDataBaseTest.php
tests/Metadata/RootMetadataTest.php
tests/Metadata/TargetsMetadataTest.php
tests/Metadata/UntrustedExceptionTrait.php
tests/TestHelpers/UtilsTrait.php
tests/Unit/Client/VerifierTest.php

`@return void` is a contradiction in terms and it has always irked me that our code base is littered with them. This PR removes all of them.

Remove every instance of `@return void`

---

src/DelegatedRole.php
src/Metadata/ConstraintsTrait.php
tests/Unit/DelegatedRoleTest.php

In #368, we removed redundant uses of the `Type` constraint. I missed a few spots, though.

Remove additional redundant uses of Symfony's Type constraint

---

composer.json
tests/Client/SnapshotHashesTest.php
tests/Client/VerifiedDownloadTest.php
tests/SignatureVerifierTest.php
tests/Unit/FileStorageTest.php

We are only using Prophecy in two places in our tests; the rest of the time, we're using PHPUnit's mocking framework. Since Prophecy necessitates additional dependencies and has some incompatibilities with PHP 8.2 (you can't set a mock's constructor arguments without triggering a language-level deprecation), I don't think we should be using two mocking frameworks. Let's remove Prophecy and rely only on PHPUnit.

Completely remove Prophecy

---

src/CanonicalJsonTrait.php
src/Metadata/MetadataBase.php
tests/Metadata/MetaDataBaseTest.php
tests/Metadata/RootMetadataTest.php
tests/Metadata/TargetsMetadataTest.php
tests/Unit/CanonicalJsonTraitTest.php

Our code base is littered with examples of us calling `json_encode()` and `json_decode()` directly, even in places that use `CanonicalJsonTrait`.
Considering how it's very important than JSON be encoded and decoded consistently (one might even say canonically) in PHP-TUF, it makes sense to always use the `CanonicalJsonTrait` methods unless there's a specific reason not to.

Consistently use CanonicalJsonTrait in our code base

---

.github/workflows/build.yml
.github/workflows/drupal-recommended-project.yml

I need this now, so that I can confirm that PHP-TUF is working before I start hacking on the plugin again.

Allow all CI workflows to be triggered manually

---

.github/workflows/specification-version-check.yml
README.md
src/Client/SignatureVerifier.php
src/Key.php
src/Role.php

Fixes #352.
I had to carefully read the spec difference (https://github.com/theupdateframework/specification/compare/v1.0.32...v1.0.33) to determine that, in fact, we're already compliant, based on this code in `SignatureVerifier::checkSignatures()`:
```
if ($role->isKeyIdAcceptable($signature['keyid']) && $this->verifySingleSignature($metadata->toCanonicalJson(), $signature)) {
$verifiedKeySignatures[$signature['keyid']] = true;
}
```
If I understand it correctly, the spec is simply being explicit that the same key cannot count more than once. We were already doing that.
So I think we're good here!

Update TUF spec to 1.0.33

---

src/Key.php
tests/FixtureBuilder/Key.php
tests/Unit/KeyTest.php

[securesystemslib still includes `keyid_hash_algorithms` when canonicalizing keys](https://github.com/secure-systems-lab/securesystemslib/blob/release-0.30.0/securesystemslib/keys.py#L435), which puts it at odds with the TUF spec, which removed all mention of `keyid_hash_algorithms`  (and which we removed accordingly in #369).
Rugged, and possibly other server-side TUF repository generators, [are using securesystemslib and therefore including `keyid_hash_algorithms` when key IDs are computed](https://gitlab.com/rugged/rugged/-/blob/main/rugged/commands/lib/verification_keys.py#L67). We need to be compatible with that. So, although it is not spec-compliant, we can hotfix this on our end until the correct fix lands in Rugged, which is for it to _explicitly_ remove `keyid_hash_algorithms` …

Temporarily restore keyid_hash_algorithms for backwards compatibility with securesystemslib

---

src/Metadata/MetadataBase.php
tests/Metadata/MetaDataBaseTest.php

Based on the specification the spec_version has to be x.y.z sadly some implementations generates x.y entries.
More information can be found in https://github.com/theupdateframework/go-tuf/issues/206#issuecomment-1020213003

Allow spec version "1.0" for compatibility with older TUF implementations

---

src/Metadata/TargetsMetadata.php
tests/Metadata/TargetsMetadataTest.php

We ran into an issue where php-tuf was unable to verify a signature of a valid targets metadata file.
After some closer investigation we realized that this was caused by a mismatch between the canonical JSON that is generated by php-tuf and the canonical JSON that the CLI tool generated for the signature.
The root cause for is the fact that "toNormalizedArray" in TargetsMetadata converted multiple properties from an array to object. Because of that, "sortKey" in the CanonicalJsonTrait did not correctly recurse into the sublevels, leaving array keys in sublevels unsorted. That leads to an invalid canonical JSON.
In this PR we removed the toNormalizedArray method and instead decided to override the toCanonicalJSON method. That also is a better fit for this specific usecase, as the casting …

Fix invalid canonical JSON of TargetsMetadata

---

src/Metadata/MetadataBase.php

This is a companion MR to https://github.com/php-tuf/php-tuf/pull/386
The combination of the two MRs, appears to almost entirely remove the php and cpu overhead of running php-tuf-enabled composer.
MetadataBase::createFromJson() is a static method that takes a JSON string, and returns an object representing the data.
When profiling a TUF-enabled Drupal core composer update, I can see MetadataBase::decodeJson() taking about 100mb of inclusive peak memory usage.
The same logic is run around 10 times on exactly the same JSON string each, this means we can reduce the overhead by about 90%.
Unfortunately given this is a static method and one that's called from various different places, the only easy way to add static caching was to add a real static variable to the class. There is probably a …

Ensure that createFromJson() only creates one object per json string.

---

src/Metadata/ConstraintsTrait.php
src/Metadata/MetadataBase.php
src/Metadata/RootMetadata.php
src/Metadata/SnapshotMetadata.php
src/Metadata/TargetsMetadata.php
src/Metadata/TimestampMetadata.php

Symfony 7.3 deprecated passing arrays of options to validation constraints, and wants named arguments instead. This is also supported by Symfony 6, so let's fix this to remove the deprecated behavior so CI can pass again.

Fix deprecations in Symfony 7.3

---

src/Client/Updater.php

Updater::searchDelegatedRolesForTarget() calls itself recursively, however it calculates the full list of delegated roles for 'bins' every time. This is causing severe CPU and memory issues when testing locally with Drupal core.
An improvement is to store the delegated roles in a class property.
For me this leads to approximately a 50% reduction in both function calls and peak memory usage when profiling composer update with xhprof. It also removes about 15 http requests from Guzzle, because it was doing the full http request and everything else to build the list for 'bins' each time.
Before:
After:

Avoid recursively looking up the same delegated roles multiple times
